<a href="https://colab.research.google.com/github/zhaoxiaoer/ml/blob/main/src/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [4]:
import torch

In [5]:
x = torch.randn(4, 5)
y = torch.randn(4, 5)
z = torch.randn(4, 5)
print(x)
print(y)
print(z)

tensor([[ 1.0199, -0.7084,  0.8308,  0.2965,  1.2211],
        [-0.8766, -0.9071,  0.6558,  2.1591,  0.4778],
        [ 2.1279, -0.9951,  3.0136,  0.1537,  0.3361],
        [ 0.1299, -0.6814, -0.7440, -0.7080,  0.0443]])
tensor([[ 1.0547, -1.2850,  0.5507, -1.0849, -0.1545],
        [-0.1651, -2.2782,  0.1615,  0.0395, -0.2292],
        [ 1.6575,  0.0345, -0.3669,  0.5801, -0.6714],
        [-0.3334,  1.6550, -0.4221,  0.7367,  0.8665]])
tensor([[ 2.0694,  1.2103,  1.0746, -1.0275,  0.5770],
        [-1.7674, -0.6899, -1.2387, -1.7475, -0.0475],
        [-1.0583, -0.3992, -0.6617, -0.0802,  0.7069],
        [-1.5609, -0.4295, -0.5251, -0.0205, -1.6894]])


In [6]:
m = torch.max(x)
print(m)

tensor(3.0136)


In [7]:
m, idx = torch.max(x, 0)
print(m)
print(idx)

tensor([ 2.1279, -0.6814,  3.0136,  2.1591,  1.2211])
tensor([2, 3, 2, 1, 0])


In [8]:
m, idx = torch.max(input=x, dim=0)
print(m)
print(idx)

tensor([ 2.1279, -0.6814,  3.0136,  2.1591,  1.2211])
tensor([2, 3, 2, 1, 0])


In [9]:
m, idx = torch.max(x, 0, False)
print(m)
print(idx)

tensor([ 2.1279, -0.6814,  3.0136,  2.1591,  1.2211])
tensor([2, 3, 2, 1, 0])


In [10]:
m, idx = torch.max(x, dim=0, keepdim=True)
print(m)
print(idx)

tensor([[ 2.1279, -0.6814,  3.0136,  2.1591,  1.2211]])
tensor([[2, 3, 2, 1, 0]])


In [25]:
model = torch.nn.Linear(5, 1).to("cuda:0")
x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float).to("cuda:0")
y = model(x)
print(y)

tensor([1.7381], device='cuda:0', grad_fn=<AddBackward0>)


In [26]:
# mismatched dimensions error
x = torch.randn(4, 5)
y = torch.randn(5, 4)
z = x + y

RuntimeError: ignored

In [27]:
# fixed
y = y.transpose(0, 1)
z = x + y
print(z)

tensor([[ 0.2048,  1.6674,  0.2685,  1.9790,  0.5171],
        [ 2.3223, -1.9094, -1.4332,  1.7807, -1.1137],
        [-1.8025, -1.1479,  0.9947, -0.0584, -1.9708],
        [ 0.7831, -0.6626,  1.9985, -0.2121, -0.8536]])


In [28]:
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0")
data = torch.randn(2048, 3, 244, 244)
out = resnet18(data.to("cuda:0"))
print(out.shape)

RuntimeError: ignored

In [31]:
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
  break
print(out.shape)

torch.Size([1, 1000])


In [45]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5, 5)
print(outs)
print(nn.functional.log_softmax(outs, dim=1))
labels = torch.tensor([1, 2, 3, 4, 0])
lossval = L(outs, labels)
print(lossval)

tensor([[-0.5696, -0.0600, -0.8992,  0.8044,  1.2292],
        [ 0.8063, -0.6292,  0.0683, -0.0058, -0.8488],
        [ 0.0692,  2.9811, -0.8935,  0.4309, -0.2538],
        [ 0.0377, -0.0201, -1.4210, -1.1448,  0.0075],
        [ 1.4186,  1.1806,  0.3650,  3.2654,  0.1411]])
tensor([[-2.5936, -2.0840, -2.9232, -1.2196, -0.7947],
        [-0.8549, -2.2904, -1.5929, -1.6670, -2.5099],
        [-3.0880, -0.1761, -4.0506, -2.7263, -3.4110],
        [-1.2393, -1.2971, -2.6980, -2.4217, -1.2695],
        [-2.1696, -2.4077, -3.2233, -0.3228, -3.4472]])
tensor(1.9684)


In [ ]:
# More on dataset and dataloader
dataset = "abcdefghijklmnopqrstuvwxyz"
for datapoint in dataset:
  print(datapoint)

In [61]:
import torch
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self, idx):
    if idx >= len(self.data):
      return self.data[idx%26].upper(), idx
    else:
      return self.data[idx], idx
  
  def __len__(self):
    return 2 * len(self.data)

dataset1 = ExampleDataset()  # create the dataset
dataloader = torch.utils.data.DataLoader(dataset=dataset1, batch_size=4, shuffle=True)
for datapoint in dataloader:
  print(datapoint)

[('u', 'K', 't', 'V'), tensor([20, 36, 19, 47])]
[('d', 'M', 'X', 'g'), tensor([ 3, 38, 49,  6])]
[('a', 'r', 'z', 'j'), tensor([ 0, 17, 25,  9])]
[('m', 'h', 'v', 'b'), tensor([12,  7, 21,  1])]
[('c', 'G', 'B', 'x'), tensor([ 2, 32, 27, 23])]
[('Z', 'D', 'U', 'f'), tensor([51, 29, 46,  5])]
[('A', 'Q', 'F', 'P'), tensor([26, 42, 31, 41])]
[('I', 'R', 'l', 's'), tensor([34, 43, 11, 18])]
[('T', 'k', 'Y', 'C'), tensor([45, 10, 50, 28])]
[('n', 'L', 'i', 'E'), tensor([13, 37,  8, 30])]
[('y', 'H', 'q', 'p'), tensor([24, 33, 16, 15])]
[('O', 'o', 'W', 'S'), tensor([40, 14, 48, 44])]
[('N', 'e', 'J', 'w'), tensor([39,  4, 35, 22])]
